version: '3.8'
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - ./data:/var/lib/postgresql/data
  web:
    build: .
    command: bundle exec rails s -p 3300 -b '0.0.0.0'
    volumes:
      - .:/app
    ports:
      - 3300:3300
    depends_on:
      - db
